### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by jasomayo** [vsoch/lessons#7]
Question on: https://github.com/vsoch/lessons/tree/master/_posts/hpc/2018-07-10-sherlock-jupyter.md#21-jupyter-notebook

After following prompts to enter and verify password, I receive an error message and the step apparently fails. Any idea why this problem occurs and what can be done to fix it?

The error message in question:
`
Traceback (most recent call last):
  File "/share/software/user/open/py-jupyter/1.0.0_py36/bin/jupyter-notebook", line 11, in <module>
    sys.exit(main())
  File "/share/software/user/open/py-jupyter/1.0.0_py36/lib/python3.6/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/share/software/user/open/py-jupyter/1.0.0_py36/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/share/software/user/open/py-jupyter/1.0.0_py36/lib/python3.6/site-packages/notebook/notebookapp.py", line 1362, in start
    super(NotebookApp, self).start()
  File "/share/software/user/open/py-jupyter/1.0.0_py36/lib/python3.6/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/share/software/user/open/py-jupyter/1.0.0_py36/lib/python3.6/site-packages/notebook/notebookapp.py", line 345, in start
    set_password(config_file=self.config_file)
  File "/share/software/user/open/py-jupyter/1.0.0_py36/lib/python3.6/site-packages/notebook/auth/security.py", line 148, in set_password
    config.NotebookApp.password = hashed_password
  File "/share/software/user/open/python/3.6.1/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/share/software/user/open/py-jupyter/1.0.0_py36/lib/python3.6/site-packages/notebook/auth/security.py", line 131, in persist_config
    with io.open(config_file, 'w', encoding='utf8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/users/jazam/.jupyter/jupyter_notebook_config.json'`

**Comment by vsoch** [comment]
If you look at the last line, it’s telling you that you are missing a config for Jupyter notebook. Try running Jupyter interactively on the cluster and learning about the config file and how you can customize it. When you’ve tried, and generated one that seems to work, try this again.
